summerProject/mainApp/urls.py
from django.conf.urls import url
from django.contrib import admin
from mainApp import views


app_name = 'mainApp'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^login/$',views.user_login,name='user_login'),
    url(r'^login/$',views.movieRate,name='movieRate'),
    url(r'^recommendor/$',views.recommendor,name='recommendor'),
]

summerProject/summerProject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from mainApp import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^mainApp/',include('mainApp.urls')),
    url(r'^logout/',views.user_logout,name='logout'),
    url(r'^movieRate/',views.movieRate,name='movieRate'),
    url(r'^recommendor/$',views.recommendor,name='recommendor')

]

summerProject/mainApp/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
# Create your models here.
class userInfo(models.Model):
    user = models.OneToOneField(User)

    def __str__(self):
        return self.user.username

class userRatings(models.Model):

    movie_id = models.IntegerField()
    title = models.CharField(max_length=200)
    user_id = models.IntegerField()
    rating = models.IntegerField()

summerProject/mainApp/forms.py
from mainApp.models import userInfo,userRatings
from django import forms
from django.contrib.auth.models import User

class userInfoForm(forms.ModelForm):
    username = forms.CharField(widget = forms.TextInput(
        attrs = {
        'type':"text",
        'class':"inputFields",
        'id':"username",
        'name':"username",
        'placeholder':"Username",
        'value':"" ,
        'oninput':"return userNameValidation(this.value)",
        'required':"True",
        }
    ))
    email = forms.EmailField(widget = forms.EmailInput(
            attrs = {
            'type':"text",
            'class':"inputFields",
            'id':"email",
            'name':"email",
            'placeholder':"Email",
            'value':"" ,
            'oninput':"return emailValidation(this.value)",
            'required':"True",
            }
        ))
    password = forms.CharField(widget = forms.TextInput(
        attrs = {
        'type':"password",
        'class':"inputFields",
        'id':"password",
        'name':"password",
        'placeholder':"Password",
        'value':"" ,
        'oninput':"return passwordValidation(this.value)",
        'required':"True",
        }
    ))
    # portfolio = forms.URLField(required = False)
    # pic = forms.ImageField(required= False)

    class Meta:
        model = User
        fields = ('username','email','password')
        help_texts = {
            'username': None,
            'email': None,
        }

# class userRatingsForm(forms.ModelForm):
#

summerProject/mainApp/views.py
from django.shortcuts import render
from mainApp.forms import userInfoForm
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(request):
    return render(request,'mainApp/index.html')

@login_required
def movieRate(request):

    return render(request,'mainApp/movieRate.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def signup(request):
    registered = False

    if request.method == "POST":
        user_form = userInfoForm(data=request.POST)

        if user_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

    else:
        user_form = userInfoForm

    return  render(request, 'mainApp/index.html',
                        {'user_form':user_form,
                         'registered':registered})


def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username,password =password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("failed log in")
            return HttpResponse("Didnt work")
    else:
        return render(request,'mainApp/login.html',{})

@csrf_exempt
def recommendor(request):
    import os

    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "summerProject.settings")

    import django
    django.setup()

    import numpy as np

        # your imports, e.g. Django models
    from mainApp.models import userRatings
    import pandas as pd

    array = request.POST.getlist("ratings[]")
    array = [array[x:x+1] for x in range(0, len(array), 1)]
    df = pd.DataFrame(columns=["movie_id", "title", "user_id", "rating"])
    for i in range(len(array)):
        df = df.append(pd.Series(np.array(array[i][0].split(",")),index=["movie_id", "title", "user_id", "rating"]),ignore_index=True)

    movie_id = userRatings.objects.values_list('movie_id', flat=True)
    movie_id = list(movie_id)

    user_id = userRatings.objects.values_list('user_id', flat=True)
    user_id = list(user_id)

    title = userRatings.objects.values_list('title', flat=True)
    title = list(title)

    rating = userRatings.objects.values_list('rating', flat=True)
    rating = list(rating)
    #
    ratings = np.column_stack((movie_id, title, user_id, rating))
    #
    ratings = pd.DataFrame(ratings, columns = ["movie_id", "title", "user_id", "rating"])
    ratings = ratings.append(df)
    #
    ratings[['movie_id','user_id','rating']] = ratings[['movie_id','user_id','rating']].apply(pd.to_numeric)
    userRatings = ratings.pivot_table(index=['user_id'],columns=['title'],values='rating',aggfunc='first')
    #
    corrMatrix = userRatings.corr()
    #
    corrMatrix = userRatings.corr(method='pearson', min_periods=100)
    #
    # myRatings = userRatings.loc[944].dropna()
    print(userRatings.loc[944].dropna())

    # simCandidates = pd.Series()
    # for i in range(0, len(myRatings.index)):
    #     # print(i)
    #     # Retrieve similar movies to this one that I rated
    #     sims = corrMatrix[myRatings.index[i]].dropna()
    #         # Now scale its similarity by how well I rated this movie
    #     sims = sims.map(lambda x: x * myRatings[i])
    #         # Add the score to the list of similarity candidates
    #     simCandidates = simCandidates.append(sims)
    #
    #     #Glance at our results so far:
    # simCandidates = simCandidates.groupby(simCandidates.index).sum()
    # simCandidates.sort_values(inplace = True, ascending = False)
    # # simCandidates = simCandidates.drop(myRatings.index)
    # simCandidates = simCandidates[0:10]
    # #
    # print("RECOMMENDATIONS.................")
    # print(simCandidates)
    return render(request,'mainApp/index.html')

summerProject/templates/mainApp/SignUp.html
<!DOCTYPE html>
{% extends "mainApp/base.html" %}
  {% block body_block %}
  <div class="signupSection">
      <div class="info">
        <h2>SeeNext</h2>
        <i class="icon ion-ios-ionic-outline" aria-hidden="true"></i>
        <p>So you know what to see next</p>
      </div>
      {% if registered %}
      <center>
        <h1>Thanks for registering</h1>
      {% else %}
      <form action="#" method="POST" class="signupForm" name="signupform">
        {% csrf_token %}
        <h2>Sign Up</h2>
        <ul class="noBullet">
          <li>
          <label for="username">User Name: </label>
          {{ user_form.username }}
            </li>
          <li>
            <label for="password">Enter Password :</label>
            {{user_form.password}}
          </li>
          <li>
            <label for="email">Enter Email :</label>
            {{user_form.email}}
          </li>
          <li id="center-btn">
            <input type="submit" id="join-btn" name="join" alt="Join" value="Join">
          </li>
        </ul>
      </form>
    </div>
    {% endif %}

    <style media="screen">
    @import url(https://fonts.googleapis.com/css?family=Open+Sans:300);
  * {
  font-family: 'Open Sans', sans-serif;
  }

  body {
  margin: 0;
  padding: 0;
  overflow: hidden;
  background: url("https://dncache-mauganscorp.netdna-ssl.com/thumbseg/1998/1998762-bigthumbnail.jpg");
  }

  .signupSection {
  background: gray;
  background-repeat: no-repeat;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 800px;
  height: 450px;
  text-align: center;
  display: flex;
  color: white;
  box-shadow: 3px 10px 20px 5px rgba(0, 0, 0, .5);
  }

  .info {
  width: 45%;
  background: rgba(20, 20, 20, .8);
  padding: 30px 0;
  border-right: 5px solid rgba(30, 30, 30, .8);
  h2 {
    padding-top: 30px;
    font-weight: 300;
  }
  p {
    font-size: 18px;
  }
  .icon {
    font-size: 8em;
    padding: 20px 0;
    color: rgba(10, 180, 180, 1);
  }
  }

  .signupForm {
  width: 70%;
  padding: 30px 0;
  background: rgba(20, 40, 40, .8);
  transition: .2s;
  h2 {
    font-weight: 300;
  }
  }

  .inputFields {
  margin: 15px 0;
  font-size: 16px;
  padding: 10px;
  width: 250px;
  border: 1px solid rgba(10, 180, 180, 1);
  border-top: none;
  border-left: none;
  border-right: none;
  background: rgba(20, 20, 20, .2);
  color: white;
  outline: none;
  }

  .noBullet {
  list-style-type: none;
  padding: 0;
  }

  #join-btn {
  border: 1px solid rgba(10, 180, 180, 1);
  background: rgba(20, 20, 20, .6);
  font-size: 18px;
  color: white;
  margin-top: 20px;
  padding: 10px 50px;
  cursor: pointer;
  transition: .4s;
  &:hover {
    background: rgba(20, 20, 20, .8);
    padding: 10px 80px;
  }
  }


    </style>
  {% endblock %}
</div>

summerProject/templates/mainApp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="{% static '/fonts/Bangers-Regular.ttf'%}" rel="stylesheet" type='text/css'>
    <link href="{% static '/css/Styling.css' %}" rel="stylesheet">
    <title></title>
  </head>
  <body>

    <nav class = "navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'index'%}">SeeNext</a>
            </div>

    <div class=" navbar-collapse collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-left">
        <!-- <li class="dropdown"><a href="#" data-toggle="dropdown">Movie<i class="icon-arrow"></i></a></li> -->
          {% if user.is_authenticated %}
          <li><a href="MovieRate.html">Profile</a></li>
          <li><a href="{% url 'movieRate' %}">Rate Some Movies!</a></li>
          <li><a href="MovieRate.html">Current Recommendations</a></li>
          <li><a class = "navbar-link" href="{% url 'logout'%}">Log Out</a></li>
          <li><form class="navbar-form navbar-left">
              <div class="form-group">
                <input id = "searchbox" type="text" class="form-control" placeholder="Search">
                  </div>
                    <button id="button" type="submit" class="btn btn-default">Submit</button>
                </form>
          </li>
          {% else %}
          <li><a class="navbar-link"href="{% url 'mainApp:signup' %}">Sign Up</a></li>
        </ul>
        <form class="navbar-form navbar-right" action="{% url 'mainApp:user_login' %}" method="post">
          {% csrf_token %}
               <div class="form-group">
                 <input type="text" placeholder="Username" class="form-control" name = "username">
               </div>
               <div class="form-group">
                 <input type="password" placeholder="Password" class="form-control" name = "password">
               </div>
               <button type="submit" class="btn btn-success">Sign in</button>
             </form>
           </div><!--/.navbar-collapse -->
         </div>
          {% endif %}
</div>
</nav>



    {% block body_block %}

    {% endblock %}

</div>
<script
   src="https://code.jquery.com/jquery-3.1.1.min.js"
   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
   crossorigin="anonymous">
   </script>

<script src="{% static 'js/myJS.js' %}"></script>
  </body>
</html>

summerProject/templates/mainApp/index.html
<!DOCTYPE html>
{% extends "mainApp/base.html" %}

  {% block body_block %}
  <div class="container">

  <div class="jumbotron">
  
      <h1>See Next: Movie Recommender <center>site!</center></h1>
      <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
    </div>

    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>Watch trailers</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Rate Movies</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
     </div>
      <div class="col-md-4">
        <h2>Leave Reviews</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      </div>
      <hr>

      <footer>
        <p >&copy; 2016 Company, Inc.</p>
      </footer>
    </div>

  </div> <!-- /container -->

  </div>
{% endblock %}

summerProject/templates/mainApp/learnJson.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>

  </head>
  <body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script type="text/javascript">
    // setup some JSON to use
    var cars = [
    	{ "make":"Porsche", "model":"911S" },
    	{ "make":"Mercedes-Benz", "model":"220SE" },
    	{ "make":"Jaguar","model": "Mark VII" }
    ];

    window.onload = function() {
    	// setup the button click
    	document.getElementById("theButton").onclick = function() {
    		doWork()
    	};
    }

    function doWork() {
    	// ajax the JSON to the server
    	$.post("receiver", cars, function(){

    	});
    	// stop link reloading the page
     event.preventDefault();
    }
    </script>
    This will send data using AJAX to Python:<br /><br />
    <a href="" id="theButton">Click Me</a>
    {{ name }}
  </body>
</html>

summerProject/templates/mainApp/login.html
{% extends "mainApp/base.html" %}
  {% block body_block %}

  <div class="jumbotron">
    <h1>Log in</h1>

    <form class="" action="{% url 'mainApp:user_login' %}" method="post">
      {% csrf_token %}

      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username">

      <label for="password">Password:</label>
      <input type="password" name="password">
      <input type="submit" name="" value="Login">
    </form>
  </div>

  {% endblock %}

summerProject/templates/mainApp/movieRate.html
<!DOCTYPE html>
{% extends "mainApp/base.html" %}
{% load staticfiles %}
  {% block body_block %}
  <div class="container">
  <div class="row">
  <div class="col-lg-4 col-xs-4"><img id = "prev" class = "img-thumbnail" src="http://www.ehypermart.in/0/images/frontend/image-not-found.png" alt=""></div>
  <div class="col-lg-4 col-xs-4"><img id = "curr" class = "img-thumbnail" src="http://www.ehypermart.in/0/images/frontend/image-not-found.png" alt=""></div>
  <div class="col-lg-4 col-xs-4"><img id = "next" class = "img-thumbnail" src="http://www.ehypermart.in/0/images/frontend/image-not-found.png" alt=""></div>

  <h3></h3>

  <div class="col-lg-4 col-xs-4"><button id = "back">Back</button></div>
  <div class="col-lg-4 col-xs-4"><button id = "rate">Rate!</button></div>
  <div class="col-lg-4 col-xs-4"><button id = "skip">Skip</button></div>

  <form  id = "form" class="stars" action="{% url 'mainApp:recommendor' %}" method="post">
  {% csrf_token %}

  <label for="rating1">1<input type="radio" name="rating" id = "rating1" value="1"></label>
  <label for="rating2">2<input type="radio" name="rating" id = "rating2" value="2"></label>
  <label for="rating3">3<input type="radio" name="rating" id = "rating3" value="3"></label>
  <label for="rating4">4<input type="radio" name="rating" id = "rating4" value="4"></label>
  <label for="rating5">5<input type="radio" name="rating" id = "rating5" value="5"></label>

  <p></p>
  <hr>

  <input class = "submitBtn" type="submit" name="Submit" value="Submit" onclick="return lol();">

  </form>
</div>

</div>

{% endblock %}
<script src="{% static 'js/stars.js' %}"></script>

summerProject/templates/mainApp/orig.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Bangers|Bowlby+One|Luckiest+Guy|Sigmar+One" rel="stylesheet">
    <link href="{% static 'css/Styling.css' %}" rel="stylesheet">
    <title></title>
  </head>
  <body>
    <div class="container">

    <nav class = "navbar navbar-default navbar-static-top">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id = "SeeNext"href="{% url 'index' %}">SeeNext</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-left">
        <!-- <li class="dropdown"><a href="#" data-toggle="dropdown">Movie<i class="icon-arrow"></i></a></li> -->
          {% if user.is_authenticated %}
          <li><a href="MovieRate.html">Profile</a></li>
          <li><a href="{% url 'movieRate' %}">Rate Some Movies!</a></li>
          <li><a href="MovieRate.html">Current Recommendations</a></li>
          <li><a class = "navbar-link" href="{% url 'logout'%}">Log Out</a></li>
          <li><form class="navbar-form navbar-left">
              <div class="form-group">
                <input id = "searchbox" type="text" class="form-control" placeholder="Search">
                  </div>
                    <button id="button" type="submit" class="btn btn-default">Submit</button>
                </form>
          </li>
          {% else %}
          <li><a class = "navbar-link" href="{% url 'mainApp:signup' %}">Sign Up</a></li>
          <li><a class="navbar-link"href="{% url 'mainApp:user_login' %}">Log In</a></li>
          {% endif %}

      </ul>
    </div>
</nav>
    {% block body_block %}

    {% endblock %}
</div>
<script
   src="https://code.jquery.com/jquery-3.1.1.min.js"
   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
   crossorigin="anonymous">
   </script>

<script src="{% static 'js/myJS.js' %}"></script>
  </body>
</html>

summerProject/templates/mainApp/results.html
<!DOCTYPE html>
{% extends "mainApp/base.html" %}
{% load staticfiles %}
{% block body_block %}

<script>
    var URL = "{% url 'results' %}";
</script>

{% endblock %}